apiVersion: v1
kind: Service
metadata:
  name: orderflow-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: orderflow-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: orderflow-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP