apiVersion: v1
kind: Service
metadata:
  name: orderflow-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: orderflow-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: orderflow-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP