"""
db.py — PostgreSQL database layer for OrderFlow.

PostgreSQL is used as the persistent relational database.
Database connection details are provided through environment variables.
"""

import os
from contextlib import contextmanager
from datetime import datetime

import psycopg
from psycopg.rows import dict_row


DB_HOST = os.environ.get("DB_HOST", "localhost")
DB_PORT = int(os.environ.get("DB_PORT", "5432"))
DB_NAME = os.environ.get("DB_NAME", "orderflow")
DB_USER = os.environ.get("DB_USER", "orderflow_user")
DB_PASSWORD = os.environ.get(
    "DB_PASSWORD",
    "orderflow_dev_password"
)


SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'customer',
    disabled INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    image TEXT,
    item_count INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    image TEXT,
    stock INTEGER DEFAULT 0,
    sku TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT UNIQUE NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id),
    customer_name TEXT,
    customer_email TEXT,
    address TEXT,
    city TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    total NUMERIC(10,2) NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id),
    product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
    name TEXT,
    price NUMERIC(10,2),
    image TEXT,
    qty INTEGER
);
"""

def init_order_sequence():
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE SEQUENCE IF NOT EXISTS order_number_seq
                START WITH 8842;
            """)


@contextmanager
def get_conn():
    """
    Open a PostgreSQL connection.

    Commit when everything succeeds.
    Roll back if an exception occurs.
    Always close the connection.
    """

    conn = psycopg.connect(
        host=DB_HOST,
        port=DB_PORT,
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASSWORD,
        row_factory=dict_row,
    )

    try:
        yield conn
        conn.commit()

    except Exception:
        conn.rollback()
        raise

    finally:
        conn.close()


def init_db():
    """
    Create database tables if they don't already exist.
    """

    with get_conn() as conn:

        with conn.cursor() as cur:

            statements = [
                statement.strip()
                for statement in SCHEMA.split(";")
                if statement.strip()
            ]

            for statement in statements:
                cur.execute(statement)

            cur.execute("""
                CREATE SEQUENCE IF NOT EXISTS order_number_seq
                START WITH 8842;
            """)

    seed()


def seed():
    """
    Insert initial demo data if the database is empty.
    """

    from auth import hash_password

    now = datetime.now().strftime(
        "%Y-%m-%dT%H:%M:%S"
    )

    with get_conn() as conn:

        with conn.cursor() as cur:

            # -------------------------------------------------
            # USERS
            # -------------------------------------------------

            cur.execute(
                "SELECT COUNT(*) AS n FROM users"
            )

            if cur.fetchone()["n"] > 0:
                return

            users = [
                (
                    "Maya Ford",
                    "maya@example.com",
                    "password123",
                    "customer",
                    0,
                ),
                (
                    "Théo Laurent",
                    "theo@example.com",
                    "password123",
                    "customer",
                    0,
                ),
                (
                    "Priya Nair",
                    "priya@example.com",
                    "password123",
                    "customer",
                    0,
                ),
                (
                    "Sam Okoye",
                    "sam@example.com",
                    "password123",
                    "customer",
                    1,
                ),
                (
                    "Ren Ito",
                    "ren@orderflow.app",
                    "admin123",
                    "admin",
                    0,
                ),
            ]

            user_ids = {}

            for name, email, pw, role, disabled in users:

                cur.execute(
                    """
                    INSERT INTO users
                    (
                        name,
                        email,
                        password_hash,
                        role,
                        disabled,
                        created_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (
                        name,
                        email,
                        hash_password(pw),
                        role,
                        disabled,
                        now,
                    ),
                )

                user_ids[email] = cur.fetchone()["id"]

            # -------------------------------------------------
            # CATEGORIES
            # -------------------------------------------------

            categories = [
                (
                    "Desk & Office",
                    "desk-office",
                    "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&q=80",
                    14,
                ),
                (
                    "Kitchen",
                    "kitchen",
                    "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&q=80",
                    9,
                ),
                (
                    "Lighting",
                    "lighting",
                    "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
                    11,
                ),
                (
                    "Storage",
                    "storage",
                    "https://images.pexels.com/photos/4464887/pexels-photo-4464887.jpeg?w=600&q=80",
                    7,
                ),
            ]

            for name, slug, image, count in categories:

                cur.execute(
                    """
                    INSERT INTO categories
                    (
                        name,
                        slug,
                        image,
                        item_count
                    )
                    VALUES (%s, %s, %s, %s)
                    """,
                    (
                        name,
                        slug,
                        image,
                        count,
                    ),
                )

            # -------------------------------------------------
            # PRODUCTS
            # -------------------------------------------------

            products = [
                (
                    "Kessel Oak Desk",
                    "Desk & Office",
                    349,
                    "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&q=80",
                    12,
                    "DSK-2201",
                ),
                (
                    "Arc Task Lamp",
                    "Lighting",
                    79,
                    "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80",
                    34,
                    "LGT-0912",
                ),
                (
                    "Modular Shelf Unit",
                    "Storage",
                    219,
                    "https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=800&q=80",
                    6,
                    "STR-3390",
                ),
                (
                    "Ceramic Pour-Over Set",
                    "Kitchen",
                    58,
                    "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&q=80",
                    22,
                    "KIT-1187",
                ),
                (
                    "Linen Desk Mat",
                    "Desk & Office",
                    34,
                    "https://images.pexels.com/photos/4464887/pexels-photo-4464887.jpeg?w=800&q=80",
                    41,
                    "DSK-2214",
                ),
                (
                    "Brass Pendant Light",
                    "Lighting",
                    132,
                    "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80",
                    9,
                    "LGT-0930",
                ),
                (
                    "Stackable Crate Trio",
                    "Storage",
                    96,
                    "https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=800&q=80",
                    17,
                    "STR-3401",
                ),
                (
                    "Enamel Storage Canisters",
                    "Kitchen",
                    44,
                    "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&q=80",
                    28,
                    "KIT-1194",
                ),
            ]

            product_ids = {}

            for (
                name,
                category,
                price,
                image,
                stock,
                sku,
            ) in products:

                cur.execute(
                    """
                    INSERT INTO products
                    (
                        name,
                        category,
                        price,
                        image,
                        stock,
                        sku
                    )
                    VALUES (%s, %s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (
                        name,
                        category,
                        price,
                        image,
                        stock,
                        sku,
                    ),
                )

                product_ids[sku] = cur.fetchone()["id"]

            # -------------------------------------------------
            # HELPER FOR ORDER ITEMS
            # -------------------------------------------------

            def item(sku, qty):

                pid = product_ids[sku]

                cur.execute(
                    """
                    SELECT name, price, image
                    FROM products
                    WHERE id=%s
                    """,
                    (pid,),
                )

                product = cur.fetchone()

                return (
                    pid,
                    product["name"],
                    product["price"],
                    product["image"],
                    qty,
                )

            # -------------------------------------------------
            # SEED ORDERS
            # -------------------------------------------------

            seed_orders = [
                (
                    "ORD-8841",
                    "maya@example.com",
                    "shipped",
                    [
                        ("DSK-2201", 1),
                        ("DSK-2214", 2),
                    ],
                ),
                (
                    "ORD-8840",
                    "theo@example.com",
                    "pending",
                    [
                        ("LGT-0912", 2),
                    ],
                ),
                (
                    "ORD-8839",
                    "priya@example.com",
                    "delivered",
                    [
                        ("STR-3390", 1),
                    ],
                ),
                (
                    "ORD-8838",
                    "sam@example.com",
                    "cancelled",
                    [
                        ("LGT-0930", 1),
                        ("STR-3401", 1),
                    ],
                ),
                (
                    "ORD-8837",
                    "maya@example.com",
                    "delivered",
                    [
                        ("KIT-1187", 1),
                    ],
                ),
            ]

            for (
                order_number,
                email,
                status,
                items,
            ) in seed_orders:

                uid = user_ids[email]

                rows = [
                    item(sku, qty)
                    for sku, qty in items
                ]

                total = sum(
                    price * qty
                    for (
                        _pid,
                        _name,
                        price,
                        _img,
                        qty,
                    ) in rows
                )

                cur.execute(
                    """
                    INSERT INTO orders
                    (
                        order_number,
                        user_id,
                        customer_name,
                        customer_email,
                        address,
                        city,
                        status,
                        total,
                        created_at
                    )
                    VALUES
                    (
                        %s, %s, %s, %s, %s,
                        %s, %s, %s, %s
                    )
                    RETURNING id
                    """,
                    (
                        order_number,
                        uid,
                        email.split("@")[0].title(),
                        email,
                        "123 Demo St",
                        "Springfield",
                        status,
                        total,
                        now,
                    ),
                )

                order_id = cur.fetchone()["id"]

                for (
                    pid,
                    name,
                    price,
                    image,
                    qty,
                ) in rows:

                    cur.execute(
                        """
                        INSERT INTO order_items
                        (
                            order_id,
                            product_id,
                            name,
                            price,
                            image,
                            qty
                        )
                        VALUES
                        (%s, %s, %s, %s, %s, %s)
                        """,
                        (
                            order_id,
                            pid,
                            name,
                            price,
                            image,
                            qty,
                        ),
                    )