apiVersion: v1
kind: Service
metadata:
  name: orderflow-backend
  namespace: orderflow
spec:
  type: ClusterIP
  selector:
    app: orderflow-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP